### ISSUE TITLE
Since killing browser.d.ts no longer works or is importable as global 'uuid' in browser

### ISSUE THREAD

**Issue by DanielJoyce** [types/npm-node-uuid#2]
Can't seem to get this to work. 

```
import {uuid} from 'node-uuid';
```

Results in error

```
Module ''node-uuid'' has no exported member 'uuid'.at line 4 col 9
```

**Comment by DanielJoyce** [comment]
Specifically, this line was crucial in brwoser.d.ts when it was clobbered.

+export var uuid: Uuid;

**Comment by rapropos** [comment]
Sorry about that. After [this conversation](https://github.com/typings/registry/pull/86), I'm not sure there is a way to have the typings behave differently when used as CommonJS modules or not. @blakeembrey: is there anything we can do here?

**Comment by blakeembrey** [comment]
There is no `uuid` export from `node-uuid`, so I don't know what you want to do here? If you're trying to use this on the browser, you don't want to be doing an import anyway and has nothing to do with `browser.d.ts`.

**Comment by rapropos** [comment]
@DanielJoyce: is there a reason you don't want to import v1 or v4 directly?

**Comment by blakeembrey** [comment]
Closing without any response.
