### ISSUE TITLE
Addition of Buffer breaks my client code

### ISSUE THREAD

**Issue by rapropos** [types/npm-node-uuid#5]
I have several Angular/Webpack applications that rely on these typings. After the big rewrite, there are new signatures for functions that rely on a `Buffer` type that break the build. I understand that a dependency on ambient node definitions has been added, but can we have a discussion as to whether this is really a net win or if there is a different way to approach the situation that doesn't ask non-node users to make their build environment pretend that they are operating under node?

I'm afraid that installing node typings might lull me into accidentally installing other modules that really won't work outside of node and I won't realize this until farther down the road than I would like.

**Comment by blakeembrey** [comment]
@rapropos There's a browser copy of the definition (https://github.com/types/npm-node-uuid/blob/master/browser.d.ts) that you can use. You can change the Typings install to follow browser resolution instead.
